// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class AccountEndpointsBindings
    {
        readonly ICloudCodeService k_Service;
        public AccountEndpointsBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task ValidateAccountData()
        {
            await k_Service.CallModuleEndpointAsync(
                "Data",
                "ValidateAccountData",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
