// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class CropEndpointsBindings
    {
        readonly ICloudCodeService k_Service;
        public CropEndpointsBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task Plant(int slotID, int gamedataID)
        {
            await k_Service.CallModuleEndpointAsync(
                "Data",
                "Plant",
                new Dictionary<string, object>()
                {
                    {"slotID", slotID},
                    {"gamedataID", gamedataID},
                });
        }

        public async Task MultiPlant(List<int> slotIDs, int gamedataID)
        {
            await k_Service.CallModuleEndpointAsync(
                "Data",
                "MultiPlant",
                new Dictionary<string, object>()
                {
                    {"slotIDs", slotIDs},
                    {"gamedataID", gamedataID},
                });
        }

        public async Task Harvest(int slotID)
        {
            await k_Service.CallModuleEndpointAsync(
                "Data",
                "Harvest",
                new Dictionary<string, object>()
                {
                    {"slotID", slotID},
                });
        }

        public async Task MultiHarvest(List<int> slotIDs)
        {
            await k_Service.CallModuleEndpointAsync(
                "Data",
                "MultiHarvest",
                new Dictionary<string, object>()
                {
                    {"slotIDs", slotIDs},
                });
        }

        public async Task Remove(int slotID)
        {
            await k_Service.CallModuleEndpointAsync(
                "Data",
                "Remove",
                new Dictionary<string, object>()
                {
                    {"slotID", slotID},
                });
        }

        public async Task MultiRemove(List<int> slotIDs)
        {
            await k_Service.CallModuleEndpointAsync(
                "Data",
                "MultiRemove",
                new Dictionary<string, object>()
                {
                    {"slotIDs", slotIDs},
                });
        }

        public async Task<string> TrackCropUpdate()
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Data",
                "TrackCropUpdate",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
