// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.

namespace Unity.Services.CloudCode.GeneratedBindings.Data
{
    public enum ItemConstants_ItemType
    {
        Crop,
        Fish,
        Building,
        Consumables,
        Other,
    }
}
