// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class GameDataEndpointsBindings
    {
        readonly ICloudCodeService k_Service;
        public GameDataEndpointsBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task SaveGameData(Data.DataConstants_GameDataType type, string ID, string data)
        {
            await k_Service.CallModuleEndpointAsync(
                "Data",
                "SaveGameData",
                new Dictionary<string, object>()
                {
                    {"type", type},
                    {"ID", ID},
                    {"data", data},
                });
        }

        public async Task<string> LoadGameData(Data.DataConstants_DataAccessibility access, string key)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Data",
                "LoadGameData",
                new Dictionary<string, object>()
                {
                    {"access", access},
                    {"key", key},
                });
        }
    }
}
