// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class GameDataEndpointsBindings
    {
        readonly ICloudCodeService k_Service;
        public GameDataEndpointsBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<string> LoadGameData(Data.DataConstants_GameDataType type, int ID)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Data",
                "LoadGameData",
                new Dictionary<string, object>()
                {
                    {"type", type},
                    {"ID", ID},
                });
        }

        public async Task<List<string>> LoadMultiGameData(Data.DataConstants_GameDataType type)
        {
            return await k_Service.CallModuleEndpointAsync<List<string>>(
                "Data",
                "LoadMultiGameData",
                new Dictionary<string, object>()
                {
                    {"type", type},
                });
        }
    }
}
