// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class ItemEndpointsBindings
    {
        readonly ICloudCodeService k_Service;
        public ItemEndpointsBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task UpdateItem(Data.DataConstants_DataOperations op, Data.ItemConstants_ItemType type, int itemID, int amount)
        {
            await k_Service.CallModuleEndpointAsync(
                "Data",
                "UpdateItem",
                new Dictionary<string, object>()
                {
                    {"op", op},
                    {"type", type},
                    {"itemID", itemID},
                    {"amount", amount},
                });
        }

        public async Task UpdateMultiItem(Data.DataConstants_DataOperations op, Data.ItemConstants_ItemType type, Dictionary<string,int> data)
        {
            await k_Service.CallModuleEndpointAsync(
                "Data",
                "UpdateMultiItem",
                new Dictionary<string, object>()
                {
                    {"op", op},
                    {"type", type},
                    {"data", data},
                });
        }
    }
}
