// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class PlayerDataEndpointsBindings
    {
        readonly ICloudCodeService k_Service;
        public PlayerDataEndpointsBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task SavePlayerData(Data.DataConstants_DataAccessibility access, string key, string value)
        {
            await k_Service.CallModuleEndpointAsync(
                "Data",
                "SavePlayerData",
                new Dictionary<string, object>()
                {
                    {"access", access},
                    {"key", key},
                    {"value", value},
                });
        }

        public async Task SaveMultiPlayerData(Data.DataConstants_DataAccessibility access, Dictionary<string,string> data)
        {
            await k_Service.CallModuleEndpointAsync(
                "Data",
                "SaveMultiPlayerData",
                new Dictionary<string, object>()
                {
                    {"access", access},
                    {"data", data},
                });
        }

        public async Task<string> LoadPlayerData(Data.DataConstants_DataAccessibility access, string key)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "Data",
                "LoadPlayerData",
                new Dictionary<string, object>()
                {
                    {"access", access},
                    {"key", key},
                });
        }

        public async Task<Dictionary<string,string>> LoadMultiPlayerData(Data.DataConstants_DataAccessibility access, List<string> keys)
        {
            return await k_Service.CallModuleEndpointAsync<Dictionary<string,string>>(
                "Data",
                "LoadMultiPlayerData",
                new Dictionary<string, object>()
                {
                    {"access", access},
                    {"keys", keys},
                });
        }

        public async Task UpdatePlayerData(Data.DataConstants_DataAccessibility access, Data.DataConstants_DataOperations op, string key, int value)
        {
            await k_Service.CallModuleEndpointAsync(
                "Data",
                "UpdatePlayerData",
                new Dictionary<string, object>()
                {
                    {"access", access},
                    {"op", op},
                    {"key", key},
                    {"value", value},
                });
        }

        public async Task UpdateMultiPlayerData(Data.DataConstants_DataAccessibility access, Data.DataConstants_DataOperations op, Dictionary<string,int> data)
        {
            await k_Service.CallModuleEndpointAsync(
                "Data",
                "UpdateMultiPlayerData",
                new Dictionary<string, object>()
                {
                    {"access", access},
                    {"op", op},
                    {"data", data},
                });
        }
    }
}
