// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.System
{
    public partial class DateTimeOffset
    {
        public DateTime DateTime;
        public DateTime UtcDateTime;
        public DateTime LocalDateTime;
        public DateTime Date;
        public int Day;
        public DayOfWeek DayOfWeek;
        public int DayOfYear;
        public int Hour;
        public int Millisecond;
        public int Microsecond;
        public int Nanosecond;
        public int Minute;
        public int Month;
        public TimeSpan Offset;
        public int TotalOffsetMinutes;
        public int Second;
        public long Ticks;
        public long UtcTicks;
        public TimeSpan TimeOfDay;
        public int Year;

        [Preserve]
        public DateTimeOffset ()
        {
        }
    }
}