// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using UnityEngine.Scripting;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings.System
{
    public partial class TimeSpan
    {
        public long Ticks;
        public int Days;
        public int Hours;
        public int Milliseconds;
        public int Microseconds;
        public int Nanoseconds;
        public int Minutes;
        public int Seconds;
        public double TotalDays;
        public double TotalHours;
        public double TotalMilliseconds;
        public double TotalMicroseconds;
        public double TotalNanoseconds;
        public double TotalMinutes;
        public double TotalSeconds;

        [Preserve]
        public TimeSpan ()
        {
        }
    }
}