// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class Communications
    {
        readonly ICloudCodeService k_Service;
        
        public Communications(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task SendMsgToPlayer(string message, string messageType, string playerId)
        {
            await k_Service.CallModuleEndpointAsync(
                "Communications",
                "SendMsgToPlayer",
                new Dictionary<string, object>()
                {
                    {"message", message},
                    {"messageType", messageType},
                    {"playerId", playerId},
                });
        }

        public async Task SendMsgToAllPlayers(string message, string messageType)
        {
            await k_Service.CallModuleEndpointAsync(
                "Communications",
                "SendMsgToAllPlayers",
                new Dictionary<string, object>()
                {
                    {"message", message},
                    {"messageType", messageType},
                });
        }
    }
}
